In [7]:
!pip install numpy

In [8]:
import numpy as np

# Ejercicios arrays

1.  Genera un *array* bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array. 

2. Crea dos *arrays* (unidimensional, bidimensional) usando el método `np.array()`. 

    Las listas para crear los *arrays* son las siguientes

    ```python
    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]
    ```

    **Bonus** Haz una pequeña descripción de cada *array* usando los métodos de exploración de *arrays* que hemos aprendido.

In [9]:
# 1.  Genera un *array* bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. 
# Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array. 

array_randint= np.random.randint(34,98,(4,3),int)
print(f'la matriz obtenida es\n\n {array_randint}\n')
print(f'Las dimensiones de la array creado es {array_randint.ndim}\n')
print(f'El tipo de de datotos dentro de la array es {array_randint.dtype}')




la matriz obtenida es

 [[53 78 48]
 [69 71 35]
 [59 36 48]
 [91 63 83]]

Las dimensiones de la array creado es 2

El tipo de de datotos dentro de la array es int32


In [10]:
#2. Crea dos *arrays* (unidimensional, bidimensional) usando el método `np.array()`.
#**Bonus** Haz una pequeña descripción de cada *array* usando los métodos de exploración de *arrays* que hemos aprendido.

lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

In [11]:
a1=np.array(lista1)
print(f'Array unidimensional\n{a1}\n')

print('DATOS ARRAY:\n')

print(f'forma: {a1.shape}')
print(f'dimensiones: {a1.ndim}')
print(f'numero de elementos {a1.size}')
print(f'tipo de elementos: {a1.dtype}')

Array unidimensional
[34 56 71 98 10]

DATOS ARRAY:

forma: (5,)
dimensiones: 1
numero de elementos 5
tipo de elementos: int32


In [12]:
a2=np.array(lista2)
print(f'array bidimensional:\n{a2}\n')

print('DATOS ARRAY:\n')

print(f'forma: {a2.shape}')
print(f'dimensiones: {a2.ndim}')
print(f'numero de elementos: {a2.size}')
print(f'tipo de elementos: {a2.dtype}')

array bidimensional:
[[23 45 89 56]
 [12 43 82 44]]

DATOS ARRAY:

forma: (2, 4)
dimensiones: 2
numero de elementos: 8
tipo de elementos: int32


# Ejercicios indexación


1. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8 (incluido). 

2. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.

In [13]:
#1. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 
a3=np.arange(50)
print('El array que usaremos es\n', a3)

El array que usaremos es
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [14]:
#- El primer elemento.
print('primer elemenot es:')
a3[0]



primer elemenot es:


0

In [15]:
#- Lo elementos que están en posición impar.
print('Elementos en la s posiciones impares:')
a3[::1]

Elementos en la s posiciones impares:


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
#- Los cuatro primeros elementos.
print('Los prijmeros 4 elementos son:')
a3[:5]

Los prijmeros 4 elementos son:


array([0, 1, 2, 3, 4])

In [17]:
#Los últimos tres elementos.
print('Los 3 ultimos elementos son:')
a3[-3:]

Los 3 ultimos elementos son:


array([47, 48, 49])

In [18]:
#Los elementos entre el 4 y el 8 (incluido). 
print('Los elementos entre el 4-8 incluido:')
a3[3:8]

Los elementos entre el 4-8 incluido:


array([3, 4, 5, 6, 7])

In [19]:
#2. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:
a4=np.random.randint(0,50,(4,5))#numpy.random.randint(low, high, size, dtype)
print('El array que usaremos es\n', a4)

El array que usaremos es
 [[24 14  0 45 20]
 [42 32 44 15 38]
 [ 7 22 30 35 19]
 [49 36 48 23  6]]


In [20]:
# - La primera fila y todas las columnas.
print('La primera fila y todas als columans son:')
a4[0]


La primera fila y todas als columans son:


array([24, 14,  0, 45, 20])

In [21]:
#Todas las filas pares.
print('todas las filas pares')
a4[1::2]

todas las filas pares


array([[42, 32, 44, 15, 38],
       [49, 36, 48, 23,  6]])

In [22]:

#La primera columna y todas las filas.

print('La primera columna y todas las filas')
a4[:,0]

La primera columna y todas las filas


array([24, 42,  7, 49])

# Ejercicios filtrados


1. Crea un *array* bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y: 

    - Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".


    - Los valores de mi array bidimensional multiplicalos por el escalar 10.


2. Crea un nuevo *array* de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiz lo siguiente:

    - Suma el primer array con el segundo.


    - Aplicar la potencia para el primer array elevado al segundo.

In [23]:
#1. Crea un *array* bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y: 
print('Creamos un array bidimensional con 20 elementos comprendidos entre 0 y 50')
a5=np.random.randint(0,50,(5,5)) #Como vamos a operar, no especificamos el tipo de valor ya que queremos por defecto sea float
a5

Creamos un array bidimensional con 20 elementos comprendidos entre 0 y 50


array([[41, 36, 28, 33, 49],
       [24, 45, 46, 37, 41],
       [23, 19,  5,  4, 27],
       [ 2,  9, 12, 39, 13],
       [32, 20,  0, 48, 24]])

In [24]:
#- Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" (O)
#y el resto por "no es mi objetivo"(NO).
condicion1=(10<a5)
condicion2=(a5<30)
resultado1=np.where((condicion1 & condicion2),'NO','O')
print('El resultado al aplicar la mascara es:\n',resultado1)

El resultado al aplicar la mascara es:
 [['O' 'O' 'NO' 'O' 'O']
 ['NO' 'O' 'O' 'O' 'O']
 ['NO' 'NO' 'O' 'O' 'NO']
 ['O' 'O' 'NO' 'O' 'NO']
 ['O' 'NO' 'O' 'O' 'NO']]


In [25]:
# - Los valores de mi array bidimensional multiplicalos por el escalar 10.
resultado2=a5*10
print('El resultado de multiplicar a5 por 10, es:\n', resultado2)


El resultado de multiplicar a5 por 10, es:
 [[410 360 280 330 490]
 [240 450 460 370 410]
 [230 190  50  40 270]
 [ 20  90 120 390 130]
 [320 200   0 480 240]]


In [27]:
#2. Crea un nuevo *array* de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiz lo siguiente:
print('Creamos un array bidimensional con 20 elementos comprendidos entre 0 y 50')
a6=np.random.randint(0,50,(5,5)) #Como vamos a operar, no especificamos el tipo de valor ya que queremos por defecto sea float
a6

Creamos un array bidimensional con 20 elementos comprendidos entre 0 y 50


array([[12, 10, 17, 49, 38],
       [18,  2,  6, 20,  3],
       [44, 21, 25, 39, 17],
       [32, 49, 14, 40, 44],
       [ 7,  3,  5, 26, 21]])

In [28]:
#- Suma el primer array con el segundo.
print(f'El primer array es:\n{a5}\n')
resultado3=np.add(a5,a6)
print('\nEl resultado de sumar las arrays anteriores, a5,a6:\n', resultado3)

El primer array es:
[[41 36 28 33 49]
 [24 45 46 37 41]
 [23 19  5  4 27]
 [ 2  9 12 39 13]
 [32 20  0 48 24]]


El resultado de sumar las arrays anteriores, a5,a6:
 [[53 46 45 82 87]
 [42 47 52 57 44]
 [67 40 30 43 44]
 [34 58 26 79 57]
 [39 23  5 74 45]]


In [29]:
#- Aplicar la potencia para el primer array elevado al segundo.
resultado4=np.power(a5,a6)
print('\nEl resultado de sumar las arrays anteriores, a5,a6:\n', resultado4)


El resultado de sumar las arrays anteriores, a5,a6:
 [[-1236507039 -1190133760           0  1716413985  1079737889]
 [          0        2025   884362304   -84138319       68921]
 [ 1212290145   972113667   167814181           0  1910090587]
 [          0 -1999808631 -1879048192  1635284161  1856643633]
 [          0        8000           0           0           0]]


In [ ]:
#np.power lee las ptencias de 10, como si fueran string. Esto se soluciona creando valores float aleatorios. 
#Each numpy data type in has a minimum and maximum value based on the number of bits. 
#From your output, it looks like your array has dtype np.int64. You can check out those min/max values using np.iinfo()

# Ejercicios funciones


1. En este ejercicio vamos a tratar de usar algunos de los métodos aprendidos. 

    - Crea un *array*, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

    - Calcula: 

        - La media de los elementos
        - La media de las columnas y redondéalo a dos decimales
        - El valor máximo de cada fila
        - El valor mínimo de cada fila
        - Hay algun valor que sea mayor que 90 en tu *array* 
        - Donde los podemos encontrar, cuáles son sus índices
        - Ordena el *array* de mayor a menor

    📝 **NOTA** En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos. 

In [31]:
print('Creamos una array con datos entre 0 y 100:')
a7=np.random.randint(0,100,(4,3))
a7

Creamos una array con datos entre 0 y 100:


array([[40, 99, 53],
       [32, 58, 15],
       [ 2, 58, 51],
       [50, 36, 83]])

In [34]:
media=np.mean(a7)
print('La media de los valores es:', round(media,2))

La media de los valores es: 48.08


In [39]:

media_columnas=np.mean(a7,axis=1)
print('La media de las columnas es:',np.round(media_columnas,2))

La media de las columnas es: [64.   35.   37.   56.33]


In [40]:
maxim=np.max(a7)
print('El valor maximo del array es:',maxim)
minim=np.min(a7)
print('El valor maximo del array es:',minim)

El valor maximo del array es: 99
El valor maximo del array es: 2


In [49]:
print('Hay algun valor que sea mayor que 90 en tu *array*:\n')
resultado=a7[a7>90]
if list(resultado) ==[]:
    print('No hay ningun valor mayor que 90')
else:
    print('Los resultados mayores de 90 son:', list(resultado))
    indices=np.where(a7>90)
    print('Los podemos encontrar en los siguinetes indices', indices)



Hay algun valor que sea mayor que 90 en tu *array*:

Los resultados mayores de 90 son: [99]
Los podemos encontrar en los siguinetes indices (array([0], dtype=int64), array([1], dtype=int64))


In [55]:
#Para ordenarlo de mayor a menor, todo el array:
#Lo pasamos a una dimension:
a7_unidimensional=a7.flatten()
print(f'El array unidimensional es:\n{a7_unidimensional}\n')

#Lo ordenamos de mayor a menor:
mayor_menor=-np.sort(-a7_unidimensional)
print(f'El array unidimensional ordenado de manor a mayor es:\n{mayor_menor}\n')

#Lo de devolvemos a su estructura anterior:
a7_ordenado=np.reshape(mayor_menor,(4,3))
print(f'El array de mayor a menor es:\n',a7_ordenado)

El array unidimensional es:
[40 99 53 32 58 15  2 58 51 50 36 83]

El array unidimensional ordenado de manor a mayor es:
[99 83 58 58 53 51 50 40 36 32 15  2]

El array de mayor a menor es:
 [[99 83 58]
 [58 53 51]
 [50 40 36]
 [32 15  2]]
