## Indexación en *arrays* unidimensionales

Como ya hemos dicho, la indexación se utiliza para acceder y manipular elementos individuales o grupos de elementos en un array. En NumPy, la indexación se realiza utilizando corchetes `[]`, al igual que hacíamos en listas. 

```python
array[i]
# donde i es el índice del elemento al que queremos acceder
```


In [1]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

In [2]:
# Imaginemos que tenemos el siguiente array unidimensional con 15 elementos
## en nuestro array

unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# si queremos acceder al primer elemento de nuestro array
print("\n---------------------------\n")
print(f"El primer elemento de nuestro array es: \n {unidimensional[0]}")

El array unidimensional que tenemos es: 
 [0.15466414 0.74124357 0.4429453  0.16248862 0.10859269 0.8193303
 0.595627   0.9315573  0.22209103 0.80825342 0.44141689 0.49798342
 0.31977266 0.03833874 0.94869692]

---------------------------

El primer elemento de nuestro array es: 
 0.15466413716584404


Bien! en caso de querer obtener o acceder a los ultimos 3 elementos podriamos hacerlo de la misma forma que haciamos con las listas.

In [3]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")


# si queremos acceder a los tres últimos elementos:
print("\n---------------------------\n")
print(f"Los tres últimos elementos de nuestro array son: \n {unidimensional[-3:]}")

El array unidimensional que tenemos es: 
 [0.88439828 0.51706322 0.07594348 0.55783837 0.55060401 0.90166389
 0.70146671 0.90830646 0.06195051 0.06447099 0.75050799 0.65929755
 0.98011174 0.4137062  0.80001065]

---------------------------

Los tres últimos elementos de nuestro array son: 
 [0.98011174 0.4137062  0.80001065]


Para una seleccion acotada de elementos, nuevamente lo hacemos de manera similiar que las listas, esta vez para los elementos ubicados desde la posicion 2 (incluido) y la posicion 4 (no incluido), MUCHA ATENCION EN COMO SE SELECCIONAN LOS ELEMENTOS!!

In [4]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# si queremos seleccionar el tercer y cuarto elemento
print("\n---------------------------\n")
print(f"El tercer y cuarto elemento de nuestro array son: \n {unidimensional[2:4]}")


El array unidimensional que tenemos es: 
 [0.42791213 0.22099181 0.18343128 0.15356766 0.58032517 0.80545918
 0.9750707  0.03767743 0.48070849 0.50280385 0.73518306 0.10160182
 0.17723571 0.20127334 0.75944253]

---------------------------

El tercer y cuarto elemento de nuestro array son: 
 [0.18343128 0.15356766]


Continuando con la seleccion de elementos, vemos que podemos combinar ya que se nos pide seleccionar todos los elementos desde el inicio hasta la posicion 10 ( recuerden que como queremos la posicion 10, entonces indicamos como fin el 11 quedando de la manera [:11]) y que a su vez deben ser en saltos de a dos posiciones, por lo que la expresion completa sera [:11:2]

In [5]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# los elementos desde el inicio hasta el 10 en saltos de dos en dos
print("\n---------------------------\n")
print(f"Los elementos desde el inicio hasta el 10 de dos en dos son: \n {unidimensional[:11:2]}")



El array unidimensional que tenemos es: 
 [0.7317626  0.64767596 0.62042063 0.56059709 0.38674266 0.85492649
 0.3410154  0.95972124 0.44521223 0.34436242 0.79109583 0.91953436
 0.68008048 0.01894294 0.79779067]

---------------------------

Los elementos desde el inicio hasta el 10 de dos en dos son: 
 [0.7317626  0.62042063 0.38674266 0.3410154  0.44521223 0.79109583]


## Indexación en *arrays* bidimensionales

En el caso de este tipo de *arrays* se acceder a elementos individuales en una matriz bidimensional utilizando la sintaxis `[fila, columna]` entre corchetes.

Los podemos entender como una lista de listas.

```python
array[i,j]
array[i][j]

# 🚨 Las dos lineas anteriores son exactamente lo mismo
# seleccionará el elemento de la fila "i" y columna "j"
```


Donde: 
- `i` --> filas

- `j` --> columnas

In [6]:
# definimos un array bidimensional
# en este caso estamos generando un array de 5 filas y 4 columnas con números aleatorios entre el 0 y el 1
bidimensional = np.random.rand(5, 4)
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# desgranemos la indexación en este tipo de arrays
# si accedemos al elemento 0 del array obtenemos a la fila que queramos de nuestro array

print(f"\nEl primer elemento de nuestro array es: \n {bidimensional[0]}")

El array bidimensional que tenemos es: 
 [[0.49894948 0.81918606 0.49995564 0.01063952]
 [0.97400453 0.882342   0.88136946 0.12250225]
 [0.66354283 0.1945655  0.80980866 0.47723235]
 [0.24480485 0.85632059 0.23936831 0.59240251]
 [0.73047092 0.55031518 0.88063376 0.2583223 ]]

El primer elemento de nuestro array es: 
 [0.49894948 0.81918606 0.49995564 0.01063952]


In [7]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# dado el resultado del paso anterior, sigamos buceando en el array, 
# en este caso querremos acceder al primer elemento del resultado anterior
# fijaos como ponemos dos indices, el primero para acceder a las filas 
# y el segundo para acceder a las columnas
# podríamos decir que es como el juego de hundir la flota
print(f"\nEl primer elemento de la primera fila de nuestro array es: \n {bidimensional[0][0]}")
print("\n-------------------------------------\n")
print(f"bidimensional[0][0] es exactamente lo mismo que bidimensional[0,0]: \n {bidimensional[0,0]}")

El array bidimensional que tenemos es: 
 [[0.49894948 0.81918606 0.49995564 0.01063952]
 [0.97400453 0.882342   0.88136946 0.12250225]
 [0.66354283 0.1945655  0.80980866 0.47723235]
 [0.24480485 0.85632059 0.23936831 0.59240251]
 [0.73047092 0.55031518 0.88063376 0.2583223 ]]

El primer elemento de la primera fila de nuestro array es: 
 0.4989494807056887

-------------------------------------

bidimensional[0][0] es exactamente lo mismo que bidimensional[0,0]: 
 0.4989494807056887


In [8]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")
# accedemos a la segunda fila, tercer columna. 
print("\n---------------------------\n")
print(f"El elemento que esta en la 2ª fila y 3ª columna es: \n {bidimensional[1,2]}")


El array bidimensional que tenemos es: 
 [[0.49894948 0.81918606 0.49995564 0.01063952]
 [0.97400453 0.882342   0.88136946 0.12250225]
 [0.66354283 0.1945655  0.80980866 0.47723235]
 [0.24480485 0.85632059 0.23936831 0.59240251]
 [0.73047092 0.55031518 0.88063376 0.2583223 ]]

---------------------------

El elemento que esta en la 2ª fila y 3ª columna es: 
 0.8813694633568555


📌 **NOTA** Cuando usamos la siguiente estructura `array[i,j]`: 

- Todo lo que haya antes de la coma se referirá a filas.


- Todo lo que haya después de la coma se referirá a columnas. 

De esta forma, si por ejemplo queremos seleccionar solo las dos primeras filas usaremos la nomenclatura que ya conocemos con los `:`. Si no especificamos nada (o solo ponemos `:`) se entiende que lo queremos todo. Por ejemplo 👇🏽

In [9]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")
# seleccionamos las dos primeras filas, y todas las columnas (no ponemos 
# nada después de la coma). 
print("\n---------------------------\n")
print(f"Las dos primeras filas con todas sus columnas son: \n {bidimensional[:2,:]}")


El array bidimensional que tenemos es: 
 [[0.49894948 0.81918606 0.49995564 0.01063952]
 [0.97400453 0.882342   0.88136946 0.12250225]
 [0.66354283 0.1945655  0.80980866 0.47723235]
 [0.24480485 0.85632059 0.23936831 0.59240251]
 [0.73047092 0.55031518 0.88063376 0.2583223 ]]

---------------------------

Las dos primeras filas con todas sus columnas son: 
 [[0.49894948 0.81918606 0.49995564 0.01063952]
 [0.97400453 0.882342   0.88136946 0.12250225]]


In [17]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# seleccionamos todas las filas y solo las tres últimas columnas
print("\n---------------------------\n")
print(f"Todas las filas y las últimas tres columnas son: \n {bidimensional[:,-3:]}")

El array bidimensional que tenemos es: 
 [[0.72392106 0.80117079 0.39905824 0.6022385 ]
 [0.86921394 0.18769465 0.72761844 0.01098491]
 [0.90781688 0.53888175 0.66061778 0.6726556 ]
 [0.07557314 0.74275994 0.64192431 0.87129239]
 [0.11393153 0.05006257 0.00643769 0.51710953]]

---------------------------

Todas las filas y las últimas tres columnas son: 
 [[0.80117079 0.39905824 0.6022385 ]
 [0.18769465 0.72761844 0.01098491]
 [0.53888175 0.66061778 0.6726556 ]
 [0.74275994 0.64192431 0.87129239]
 [0.05006257 0.00643769 0.51710953]]


## Indexación en *arrays* tridimensionales

De la misma forma que en los bidimensionales, el los mutidimensionales podemos acceder a sus elementos de dos formas: 

```python
array[i,j,k]
array[i][j][k]
```

- i → *array* al que queremos acceder 


- j → fila de nuestro *array* al que queremos acceder


- k → columna de nuestro *array* al que queremos acceder

    ![3d-array-index.png](https://github.com/Adalab/data_imagenes/blob/main/Modulo-2/NumPy/index_numpy_multidimensional.png?raw=true)

In [10]:
# definimos un array tridimensional
# en este caso estamos creando un array de números enteros entre el 10 y el 100 con
# 2 matrices, 3 filas y 5 columnas
tridimensional = np.random.randint(10,100, (2,3,5))
print(f"El array multidimensional que tenemos es: \n {tridimensional}")

# accedemos al primer array y al elemento que está en la fila 2 y la columna 4
print("\n---------------------------\n")
print(f"El elemento de la 1ª matriz, 2ª fila y 4ª columna es : \n {tridimensional[0,1,3]}")

El array multidimensional que tenemos es: 
 [[[53 55 39 16 97]
  [93 72 56 36 69]
  [64 12 76 44 39]]

 [[36 78 84 75 72]
  [59 97 19 77 30]
  [81 56 79 63 33]]]

---------------------------

El elemento de la 1ª matriz, 2ª fila y 4ª columna es : 
 36


In [11]:
print(f"El array multidimensional que tenemos es: \n {tridimensional}")

# primer array primera fila y todas las columnas
print("\n---------------------------\n")
print(f"Los elementos del 1ª matriz, 1ª fila y todas las columnas  : \n {tridimensional[0,0, :]}")


El array multidimensional que tenemos es: 
 [[[53 55 39 16 97]
  [93 72 56 36 69]
  [64 12 76 44 39]]

 [[36 78 84 75 72]
  [59 97 19 77 30]
  [81 56 79 63 33]]]

---------------------------

Los elementos del 1ª matriz, 1ª fila y todas las columnas  : 
 [53 55 39 16 97]


# Ejercicios


1. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8 (incluido). 

2. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.


In [6]:
#1. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

uni = np.random.random_sample(50)
print("\n",uni )


 [0.0508314  0.34556278 0.15971028 0.56646827 0.44484189 0.23745921
 0.30687629 0.69571678 0.80621107 0.62648794 0.42989235 0.56429298
 0.6991178  0.02802267 0.48826082 0.19836947 0.95390482 0.34183465
 0.93825055 0.75495269 0.04273854 0.43218819 0.50633584 0.82753505
 0.95033396 0.8457296  0.41444183 0.4071503  0.75245179 0.37191734
 0.62054438 0.37804753 0.26337304 0.52605899 0.49901684 0.92414194
 0.16926873 0.1169627  0.84871333 0.4968776  0.93899434 0.43232913
 0.62588035 0.87803791 0.87122929 0.54283383 0.19739063 0.80884322
 0.11293997 0.35004331]


In [4]:
# El primer elemento.
uni[0]


0.9964918415473683

In [7]:
#  Lo elementos que están en posición impar.
uni[0::2]


array([0.0508314 , 0.15971028, 0.44484189, 0.30687629, 0.80621107,
       0.42989235, 0.6991178 , 0.48826082, 0.95390482, 0.93825055,
       0.04273854, 0.50633584, 0.95033396, 0.41444183, 0.75245179,
       0.62054438, 0.26337304, 0.49901684, 0.16926873, 0.84871333,
       0.93899434, 0.62588035, 0.87122929, 0.19739063, 0.11293997])

In [9]:
 #   - Los cuatro primeros elementos.
uni[:4]


array([0.0508314 , 0.34556278, 0.15971028, 0.56646827])

In [12]:
#    - Los últimos tres elementos.
uni[-3:]

array([0.80884322, 0.11293997, 0.35004331])

In [14]:
# Los elementos entre el 4 y el 8 (incluido). 
uni[3:8]


array([0.56646827, 0.44484189, 0.23745921, 0.30687629, 0.69571678])

In [19]:
#2. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:
dos_dimensiones=np.random.rand(4,5)
print("\n",dos_dimensiones)



 [[0.94911388 0.2826457  0.79560758 0.3314637  0.90776545]
 [0.31981998 0.33613852 0.547709   0.93272593 0.62966423]
 [0.11751162 0.53189478 0.47599073 0.85455317 0.09654413]
 [0.73806868 0.84003971 0.47029409 0.47600092 0.32240551]]


In [25]:
# La primera fila y todas las columnas.
dos_dimensiones [0, : ]


array([0.94911388, 0.2826457 , 0.79560758, 0.3314637 , 0.90776545])

In [23]:
# Todas las filas pares.
dos_dimensiones[ ::2, ]

array([[0.94911388, 0.2826457 , 0.79560758, 0.3314637 , 0.90776545],
       [0.11751162, 0.53189478, 0.47599073, 0.85455317, 0.09654413]])